--- 
abstract: a component for your own BBS client
author: sunnavy <sunnavy@gmail.com>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.650
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: BBS-Perm
no_index: 
  directory: 
    - examples
    - inc
    - t
requires: 
  Encode: 0
  Expect: 0
  File::Slurp: 0
  Gnome2::Vte: 0.07
  Gtk2: 1.144
  IP::QQWry: 0.0.13
  Regexp::Common: 2.120
  UNIVERSAL::moniker: 0
  UNIVERSAL::require: 0
  perl: 5.8.0
  version: 0
version: !!perl/hash:version 
  qv: 1
  version: 
    - 0
    - 0
    - 3
