---
abstract: 'a component for your own BBS client'
author:
  - 'sunnavy  C<< <sunnavy@gmail.com> >>'
  - 'sunnavy <sunnavy@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: BBS-Perm
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Encode: 0
  Expect: 0
  File::Slurp: 0
  Gnome2::Vte: 0.07
  Gtk2: 1.144
  IP::QQWry: 0.0.13
  Regexp::Common: 2.120
  UNIVERSAL::moniker: 0
  UNIVERSAL::require: 0
  perl: 5.8.0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.001000
