---
global:  
    term:
        # Default values for all sites
        protocol: ssh
        port: 22
        agent: 'bbs-perm-agent'
        font:
            family: 'courier new'
            size: 20
            anti_alias: 'force-disable'
        encoding: gbk
        timeout: 60
                # send some character every 60 seconds for anti-idle
        background_file: /home/picture/camel.jpg
        background_transparent: 0
        mouse_autohide: 0
        color:
            background: black
            foreground: white
    uri:
        default: 'http://www.google.com'
        browser: 'firefox -new-tab'
    ip:
        qqwry: /opt/QQWry.Dat
    feed:
        label: Feed
    title: 'bbs-perm'
    #default title
newsmth:
    shortcut: 'M-s'
        # use Alt+s to connect
    title: sunnavy@newsmth
    site: 60.2.251.8
    username: sunnavy
    password: cGFzc3dvcmQ=
            # use MIME::Base64; encode_base64('password')

zixia:
    shortcut: 'M-c'
    title: sunnavy@zixia
    site: 211.99.222.55
    username: sunnavy
    password: cGFzc3dvcmQ=
